spring:
  redis:
    host: redis.haohaoli.cn
    port: 6399
    database: 0
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/