server:
  port: 8677
spring:
  application:
    name: collection-service
  redis:
    host: redis.haohaoli.cn
    port: 6399
    database: 0
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
logging:
  level:
    cn.haohaoli.weather.collection: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/