server:
  port: 8765
spring:
  application:
    name: core-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    city:
      path: /city/**
      serviceId: city-service
    data:
      path: /data/**
      serviceId: data-service