server:
  port: 8989
spring:
  application:
    name: core-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/27392/weather-cloud/tree/master/core-config-repo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/